name: Java CI

on: [push]

jobs:
  test:
    timeout-minutes: 5
    strategy:
      matrix:
        jdk: ['8', '11', '17', '19']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: ${{ runner.os }}-deps-${{ matrix.submodule_hash }}-${{ hashFiles('**/pom.xml') }}-${{ hashFiles('**/deps.edn') }} 
          restore-keys: |
            ${{ runner.os }}-deps-${{ matrix.submodule_hash }}-${{ hashFiles('**/pom.xml') }}-${{ hashFiles('**/deps.edn') }}
            ${{ runner.os }}-deps-${{ matrix.submodule_hash }}-${{ hashFiles('**/pom.xml') }}-
            ${{ runner.os }}-deps-${{ matrix.submodule_hash }}-
            ${{ runner.os }}-deps-
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean test
  all-pr-checks:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - run: echo "All tests pass!"
  deploy:
    needs: all-pr-checks
    env:
      DEPLOY_JDK: 11
    if: ${{ github.ref == 'refs/heads/futjure-release'
            && github.repository == 'futjure/futjure'
            && github.event_name == 'push'
         }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: ${{ runner.os }}-deps-${{ matrix.submodule_hash }}-${{ hashFiles('**/pom.xml') }}-${{ hashFiles('**/deps.edn') }} 
          restore-keys: |
            ${{ runner.os }}-deps-${{ matrix.submodule_hash }}-${{ hashFiles('**/pom.xml') }}-${{ hashFiles('**/deps.edn') }}
            ${{ runner.os }}-deps-${{ matrix.submodule_hash }}-${{ hashFiles('**/pom.xml') }}-
            ${{ runner.os }}-deps-${{ matrix.submodule_hash }}-
            ${{ runner.os }}-deps-
      - name: Set up JDK ${{ env.DEPLOY_JDK }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.DEPLOY_JDK }}
      - name: Configure settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>clojars</id><username>${{ secrets.CLOJARS_USER }}</username><password>${{ secrets.CLOJARS_PASSWORD }}</password></server></servers></settings>" > ~/.m2/settings.xml
      - name: Deploy
        run: mvn clean deploy -Dmaven.test.skip=true
      - run: rm -f ~/.m2/settings.xml
        if: ${{ always() }}
